### ISSUE TITLE
Resize token embedding

### ISSUE THREAD

**Issue by hieudx149** [hltcoe/ColBERT-X#1]
Hi there,
in [here](https://github.com/hltcoe/ColBERT-X/blob/main/xlmr_colbert/modeling/colbert.py#L31) why you comment this line, when you add new token you need to resize toke embedding ?

**Comment by eugene-yang** [comment]
It's because we decided to resize it in the [training script](https://github.com/hltcoe/ColBERT-X/blob/main/xlmr_colbert/training/training.py#L50) and the [function](https://github.com/hltcoe/ColBERT-X/blob/main/xlmr_colbert/evaluation/load_model.py#L21) for loading the trained model.

**Comment by hieudx149** [comment]
I see, thank for your answer
