### ISSUE TITLE
Module not found error during indexing.

### ISSUE THREAD

**Issue by cramraj8** [hltcoe/ColBERT-X#2]
I am getting following error when trying to run the indexing. Anyone has any idea ?
```
import colbert.utils.distributed as distributedimport colbert.utils.distributed as distributed
ModuleNotFoundErrorModuleNotFoundError: : No module named 'colbert'No module named 'colbert'
```
Should I have to install the package like ColBERT ?

**Comment by surajnair04** [comment]
No, you don't need to. I have changed all the existing module references to colbert. 
The code should work fine now. 
Feel free to open the issue if it is still not working.
