### ISSUE TITLE
Differences in Num of Topics found in HC4 GitHub page and number reported in ColBERT-X paper

### ISSUE THREAD

**Issue by cramraj8** [hltcoe/ColBERT-X#3]
@eugene-yang  @dlawrie , ColBERT-X paper reports 50 topics for HC4 Persian & Chinese. But at HC4 GitHub, train, dev, and test respectively has 27, 15, and 118 topics. In order to reproduce the ColBERT-X results, which topic set should I be using ?

**Comment by surajnair04** [comment]
You should use the test set (118 topics) to reproduce the results.
The 50 topics in HC4 Persian and Chinese indicate the ones that have at least one relevant document.
