### ISSUE TITLE
Evaluation guide 

### ISSUE THREAD

**Issue by jinruiyang** [hltcoe/ColBERT-X#4]
Dear authors,

I read your paper 'Multilingual ColBERT-X' and the evaluation and test on CLEF are very impressed. But there isn't any description in README.
Could you update the detailed instructions for inference and PRF?  
Thanks!

**Comment by eugene-yang** [comment]
Oops, sorry for missing your issue. 
We put together a tutorial on how to use the package here. 
https://github.com/hltcoe/clir-tutorial with a pretty nice [notebook](https://github.com/hltcoe/clir-tutorial/blob/main/notebooks/clir_tutorial_plaidx.ipynb).

Hope this would help. 

And for the PRF part, we currently don't have that ability in our codebase. 
But you can use the version in pyterrier: https://github.com/terrierteam/pyterrier_colbert
