### ISSUE TITLE
About "hltcoe/tdist-msmarco-scores" on huggingface

### ISSUE THREAD

**Issue by aken12** [hltcoe/ColBERT-X#9]
Hi, I recently read the "Translate-Distill" paper and found it to be excellent work! 

From my understanding, the Eng-Eng scores by mT5-XXL are the effective teacher scores. I noticed that the Huggingface repository "hltcoe/tdist-msmarco-scores" provides teacher scores, but I couldn't find the scores for English-English pairs. 
Are you planning to publish these?

**Comment by eugene-yang** [comment]
Ah sorry for the delay. Yes we are planning to release that. Let me get back to you in couple days after I push that.

**Comment by eugene-yang** [comment]
@aken12 It's now at https://huggingface.co/datasets/hltcoe/tdist-msmarco-scores/blob/main/mt5xxl-monot5-mmarco-engeng.jsonl.gz.
